"""add class and class inquiry model, and class relationships to user model

Revision ID: 0116cfd1f128
Revises: 8659618cd84b
Create Date: 2021-05-03 18:58:39.029304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0116cfd1f128'
down_revision = '8659618cd84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availability', 'tutor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'cognitoId',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'cognitoId',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('availability', 'tutor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
