"""add avail series to user model

Revision ID: 0767912f44ef
Revises: 255aafca6a91
Create Date: 2021-11-16 17:23:43.445619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0767912f44ef'
down_revision = '255aafca6a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
