"""use camelCase instead of snake_case

Revision ID: 0b4bdb700843
Revises: 4680feb46ac5
Create Date: 2021-02-06 20:29:45.663500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b4bdb700843'
down_revision = '4680feb46ac5'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('users', 'cognito_id', new_column_name='cognitoId')
    op.alter_column('users', 'first_name', new_column_name='fisrtName')
    op.alter_column('users', 'last_name', new_column_name='lastName')
    op.alter_column('users', 'registered_on', new_column_name='registeredOn')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('cognitoId', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('firstName', sa.String(length=65), nullable=True))
    # op.add_column('users', sa.Column('lastName', sa.String(length=65), nullable=True))
    # op.add_column('users', sa.Column('registeredOn', sa.DateTime(), nullable=False))
    # op.drop_constraint('users_cognito_id_key', 'users', type_='unique')
    # op.create_unique_constraint(None, 'users', ['cognitoId'])
    # op.drop_column('users', 'registered_on')
    # op.drop_column('users', 'first_name')
    # op.drop_column('users', 'last_name')
    # op.drop_column('users', 'cognito_id')
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('users', 'cognitoId', new_column_name='cognito_id')
    op.alter_column('users', 'fisrtName', new_column_name='first_name')
    op.alter_column('users', 'lastName', new_column_name='last_name')
    op.alter_column('users', 'registeredOn', new_column_name='registered_on')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('cognito_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # op.add_column('users', sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'users', type_='unique')
    # op.create_unique_constraint('users_cognito_id_key', 'users', ['cognito_id'])
    # op.drop_column('users', 'registeredOn')
    # op.drop_column('users', 'lastName')
    # op.drop_column('users', 'firstName')
    # op.drop_column('users', 'cognitoId')
    # ### end Alembic commands ###
