"""use camelCase in models constructor

Revision ID: 1256fe869399
Revises: 0b4bdb700843
Create Date: 2021-02-06 21:03:04.357709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1256fe869399'
down_revision = '0b4bdb700843'
branch_labels = None
depends_on = None


### Note, this one is really dumb. I had left user model taking snake case inputs into constructor,
### but decided against that. Then when I changed that, I noticed the typo below. This typo was initiated
### in 0b4bdb700843_use_camelcase_instead_of_snake_case.py, and now I'm just gonna fix it here..


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('firstName', sa.String(length=65), nullable=True))
    # op.drop_column('users', 'fisrtName')
    # ### end Alembic commands ###
    op.alter_column('users', 'fisrtName', new_column_name='firstName')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('fisrtName', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
    op.alter_column('users', 'firstName', new_column_name='fisrtName')
