"""change grade to integer

Revision ID: 1a8a61ce39b4
Revises: b12456861668
Create Date: 2021-05-30 21:00:36.168889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8a61ce39b4'
down_revision = 'b12456861668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.INTEGER,
               nullable=False,
               postgresql_using='grade::integer')

    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###

    op.alter_column('users', 'grade',
               existing_type=sa.INTEGER,
               type_=sa.VARCHAR(length=15),
               nullable=False,
               postgresql_using='grade::integer')

    # ### end Alembic commands ###
