"""actually, add tutor to avail series, fk to user

Revision ID: 242ed7bed0bf
Revises: 757d393fdc14
Create Date: 2021-11-16 17:58:11.298826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242ed7bed0bf'
down_revision = '757d393fdc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
