"""create availability series

Revision ID: 255aafca6a91
Revises: 6bb5912581f7
Create Date: 2021-11-05 19:47:50.898689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255aafca6a91'
down_revision = '6bb5912581f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('availability', sa.Column('availabilitySeries', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'availability', 'availability_series', ['availabilitySeries'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.drop_column('availability', 'availabilitySeries')
    op.drop_table('availability_series')
    # ### end Alembic commands ###
