"""add class and class inquiry model, and class relationships to user model

Revision ID: 291c4c478f1c
Revises: 0116cfd1f128
Create Date: 2021-05-03 20:54:13.785424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291c4c478f1c'
down_revision = '0116cfd1f128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.Column('teacher', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['teacher'], ['users.cognitoId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class_association',
    sa.Column('student_id', sa.String(length=255), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.cognitoId'], )
    )
    op.create_table('tutor_class_association',
    sa.Column('tutor_id', sa.String(length=255), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.cognitoId'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_class_association')
    op.drop_table('student_class_association')
    op.drop_table('class')
    # ### end Alembic commands ###
