"""add repeating avail model

Revision ID: 320b6941d648
Revises: bb12ed5a8f46
Create Date: 2021-11-05 19:29:34.839120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320b6941d648'
down_revision = 'bb12ed5a8f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repeating_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('availability', sa.Column('repeatingAvailability', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'availability', 'repeating_availability', ['repeatingAvailability'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.drop_column('availability', 'repeatingAvailability')
    op.drop_table('repeating_availability')
    # ### end Alembic commands ###
