"""add cognito id to user table

Revision ID: 4680feb46ac5
Revises: fefa49e6f3e1
Create Date: 2021-02-05 19:27:51.747372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4680feb46ac5'
down_revision = 'fefa49e6f3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['cognito_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cognito_id')
    # ### end Alembic commands ###
