"""add tutor field to avail series, fk to user table

Revision ID: 757d393fdc14
Revises: 0767912f44ef
Create Date: 2021-11-16 17:57:13.639146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757d393fdc14'
down_revision = '0767912f44ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
