"""initial attempt at groups

Revision ID: 8c282ba6a9ab
Revises: f3d17d9b9391
Create Date: 2021-11-18 11:30:23.105866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c282ba6a9ab'
down_revision = 'f3d17d9b9391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.Column('parentGroup', sa.Integer(), nullable=True),
    sa.Column('groupOwner', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['groupOwner'], ['users.cognitoId'], ),
    sa.ForeignKeyConstraint(['parentGroup'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_admins_link',
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.cognitoId'], ),
    sa.PrimaryKeyConstraint('groupId', 'userId')
    )
    op.create_table('group_members_link',
    sa.Column('groupId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.cognitoId'], ),
    sa.PrimaryKeyConstraint('groupId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members_link')
    op.drop_table('group_admins_link')
    op.drop_table('group')
    # ### end Alembic commands ###
