"""fix groups attempt 1

Revision ID: 9b594250a87b
Revises: 8c282ba6a9ab
Create Date: 2021-11-19 09:59:03.977416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b594250a87b'
down_revision = '8c282ba6a9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
