"""add to user model

Revision ID: b12456861668
Revises: 0116cfd1f128
Create Date: 2021-05-29 18:30:45.752865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12456861668'
down_revision = '0116cfd1f128'
branch_labels = None
depends_on = None


def upgrade():
    ## Note: had to delete creation of class and inquiry tables, even though I deleted them from the models package
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('parentEmail', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('parentName', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    op.alter_column('users', 'school',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'school',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'parentName')
    op.drop_column('users', 'parentEmail')
    op.drop_column('users', 'age')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
