"""create avail request table

Revision ID: bb12ed5a8f46
Revises: 1a8a61ce39b4
Create Date: 2021-08-17 20:21:33.073444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb12ed5a8f46'
down_revision = '1a8a61ce39b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fromUser', sa.String(length=255), nullable=False),
    sa.Column('forAvailability', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=31), nullable=False),
    sa.ForeignKeyConstraint(['forAvailability'], ['availability.id'], ),
    sa.ForeignKeyConstraint(['fromUser'], ['users.cognitoId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_request')
    # ### end Alembic commands ###
