"""starstar actually starstart add inquiry table

Revision ID: e20982861cf4
Revises: 291c4c478f1c
Create Date: 2021-05-09 11:26:55.360890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20982861cf4'
down_revision = '291c4c478f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fromUser', sa.String(length=255), nullable=False),
    sa.Column('forUser', sa.String(length=255), nullable=False),
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STUDENT', 'TUTOR', name='typeenum'), nullable=True),
    sa.Column('denied', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classId'], ['class.id'], ),
    sa.ForeignKeyConstraint(['forUser'], ['users.cognitoId'], ),
    sa.ForeignKeyConstraint(['fromUser'], ['users.cognitoId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry')
    # ### end Alembic commands ###
