"""actuallyx2, add tutor to avail series, fk to user

Revision ID: f3d17d9b9391
Revises: 242ed7bed0bf
Create Date: 2021-11-16 17:59:21.697057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d17d9b9391'
down_revision = '242ed7bed0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_series', sa.Column('tutor', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'availability_series', 'users', ['tutor'], ['cognitoId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availability_series', type_='foreignkey')
    op.drop_column('availability_series', 'tutor')
    # ### end Alembic commands ###
